steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT}/runpyapp:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT}/runpyapp:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
    - 'run'
    - 'deploy'
    - 'runpyapp'
    - '--image'
    - 'gcr.io/${_PROJECT}/runpyapp:$SHORT_SHA'
    - '--region'
    - 'us-central1'
    - '--port'
    - '8000'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/${_PROJECT}/runpyapp:$SHORT_SHA'

substitutions:
  _PROJECT: kubernetes-gcp-383911
  _REPO_NAME: github_masudd11_deploy-cloud-run

options:
    # substitutions_option: 'ALLOW_LOOSE'
    logging: 'CLOUD_LOGGING_ONLY'