steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
    timeout: '1600s'

substitutions:
  _PROJECT: kubernetes-gcp-383911
  _REPO_NAME: github_masudd11_app-engine-cloud-build

options:
    # substitutions_option: 'ALLOW_LOOSE'
    logging: 'CLOUD_LOGGING_ONLY'